package demo.models;



import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author cherry
 */
@Entity
@Table(name = "message")
public class Message {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  private long id;
    
  // The commnetor's name
  //@NotNull
  private String userName;
  
  // The commnetor's email
  private String userEmail;

  //The message content
  private String messageContent;
  
  //The message time
  private Date messageDate;



  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  public Message() { }
  
  public Message(String userEmail, String userName, String messageContent) {
	super();
	this.userEmail = userEmail;
	this.userName = userName;
	this.messageContent = messageContent;
	this.messageDate=new Date();  //the messageDate got the value everytime the consrtuctor is called
  }

// Getter and setter methods
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }


  public String getUserEmail() {
		return userEmail;
	}
	
  public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}
  
  @Column(name="USER_NAME")
  public String getUserName() {
		return userName;
	}
	
  public void setUserName(String userName) {
		this.userName = userName;
	}
	
  @Column(columnDefinition="TEXT")
  public String getMessageContent() {
		return messageContent;
	  }

  public void setMessageContent(String messageContent) {
	this.messageContent = messageContent;
  }
  
  //@Column(name="message_creation_time",columnDefinition="DATETIME")
  @Column(name="message_creation_time",columnDefinition="TIMESTAMP WITH TIME ZONE")
  public Date getMessageDate() {
	return messageDate;
  }

  public void setMessageDate(Date createTime) {  
	this.messageDate = createTime;
  }
  
} 